"""empty message

Revision ID: 0bc812f9ad5d
Revises: 7542b127b71f
Create Date: 2022-10-13 16:36:02.020499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0bc812f9ad5d"
down_revision = "7542b127b71f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("comment_model", schema=None) as batch_op:
        batch_op.alter_column("post_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("user_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.create_foreign_key(
            "fk_comment_model_post_id", "post_model", ["post_id"], ["id"]
        )
        batch_op.create_foreign_key(
            "fk_comment_model_user_id", "user_model", ["user_id"], ["id"]
        )

    with op.batch_alter_table("post_model", schema=None) as batch_op:
        batch_op.alter_column("author", existing_type=sa.INTEGER(), nullable=True)
        batch_op.create_foreign_key(
            "fk_post_model_author", "user_model", ["author"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post_model", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.alter_column("author", existing_type=sa.INTEGER(), nullable=False)

    with op.batch_alter_table("comment_model", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.alter_column("user_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("post_id", existing_type=sa.INTEGER(), nullable=False)

    # ### end Alembic commands ###
