"""empty message

Revision ID: 987c3cbb5ef1
Revises: 0bc812f9ad5d
Create Date: 2022-10-13 16:38:22.708577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '987c3cbb5ef1'
down_revision = '0bc812f9ad5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment_model', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comment_model_post_id', type_='foreignkey')
        batch_op.drop_constraint('fk_comment_model_user_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_comment_model_post_id', 'post_model', ['post_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_comment_model_user_id', 'user_model', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('post_model', schema=None) as batch_op:
        batch_op.drop_constraint('fk_post_model_author', type_='foreignkey')
        batch_op.create_foreign_key('fk_post_model_author', 'user_model', ['author'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_model', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_post_model_author', 'user_model', ['author'], ['id'])

    with op.batch_alter_table('comment_model', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_comment_model_user_id', 'user_model', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_comment_model_post_id', 'post_model', ['post_id'], ['id'])

    # ### end Alembic commands ###
